### ISSUE TITLE
Make Logging Built-in Module 

### ISSUE THREAD

**Issue by Ma-wa-re** [strinking/futaba#8]
Make a cog for the bot that manages all guild logging.
Needs to be able to configure what the guild whats logged and in what channel/channels.

Info that should be logged:
- Member joins/leaves
- Manual kicks/bans/unbans
- Message deletes
- Admin bot command (Make a function or something that commands can use to send info to log)

Possible info that can be logged:
- Message edits
- Edits in members roles
- Member nickname changes
- Channel edits
- Guild edits

**Comment by Ma-wa-re** [comment]
This needs #7 to be completed first before work can be done on it

**Comment by ammongit** [comment]
To clarify: logging is no longer a random cog because it's going to be the abstract framework for how we allow bot output to channels. Configuration will allow administrators to direct whatever kinds of traffic where they want.

I said it could be path-based, where you have something like:
`#staff-log : /moderation, /join/suspicious`
where it captures all moderation logs and suspicious joins

We'll still have to discuss about logging levels or how we'll name paths.

**Comment by ammongit** [comment]
Fixed in #48
